# Generated by Django 2.1.7 on 2019-04-12 05:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=16)),
                ('intro', models.TextField(blank=True)),
                ('status', models.CharField(max_length=16)),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 4, 12, 5, 55, 41, 925484, tzinfo=utc))),
                ('updated', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='分类', to='category.Category')),
                ('reviewers', models.ManyToManyField(related_name='review_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wr_code',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CodeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('body', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='codemg.Code')),
            ],
            options={
                'db_table': 'wr_code_comment',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CodePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16)),
                ('body', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(max_length=16)),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 4, 12, 5, 55, 41, 926443, tzinfo=utc))),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='codemg.Code')),
            ],
            options={
                'db_table': 'wr_code_post',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='codecomment',
            name='code_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_post_comments', to='codemg.CodePost'),
        ),
        migrations.AddField(
            model_name='codecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
