# Generated by Django 2.1.7 on 2019-04-12 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codemg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 6, 51, 22, 159359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 6, 51, 22, 160360, tzinfo=utc)),
        ),
    ]
