# Generated by Django 2.1.7 on 2019-04-13 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codemg', '0004_auto_20190412_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='reviewers',
        ),
        migrations.AlterField(
            model_name='code',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorycode', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='code',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 9, 11, 34, 80221)),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 9, 11, 34, 81216)),
        ),
    ]
