# Generated by Django 2.1.7 on 2019-04-15 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemg', '0005_auto_20190413_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='wenku',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 14, 55, 53, 365147)),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 14, 55, 53, 366142)),
        ),
    ]
