# Generated by Django 2.1.7 on 2019-04-15 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemg', '0007_auto_20190415_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='star',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 17, 34, 26, 479930)),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 17, 34, 26, 480928)),
        ),
    ]
