# Generated by Django 2.0.3 on 2019-05-07 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemg', '0013_auto_20190430_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 17, 58, 32, 970338)),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 17, 58, 32, 972338)),
        ),
    ]
