# Generated by Django 2.0.3 on 2019-05-07 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemg', '0015_auto_20190507_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 18, 1, 19, 425859)),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 18, 1, 19, 427859)),
        ),
    ]
