# Generated by Django 2.0.3 on 2019-05-07 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemg', '0020_auto_20190507_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 22, 48, 54, 27111)),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 22, 48, 54, 28111)),
        ),
    ]
